name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: display env
      run: |
        env;echo "[info] grep env"; env | grep 7;echo "[info] fininsh grep env";ls;pwd; git branch -a; 
    - name: get pylint config
      run: |
        wget --no-check-certificate https://tools.mindspore.cn/tools/check/pylint/rules/pylintrc
    - name: Analysing the code with pylint
      run: |
        pylint  --rcfile=pylintrc $(git ls-files '*.py')
